name: Vertical Media
favicon: null
layout_spectrum: 0.51712
typography_spectrum: 0.7642572906333953
title: Vertical Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc3127'
    - '#120002'
    - '#952421'
    - '#6d0d0d'
    - '#de2019'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.3145056995563209
  rhythmicContrast: 0.25
purpose: []
